### ISSUE TITLE
cannot use the element panel-content item

### ISSUE THREAD

**Issue by giannik** [RadioSystems/RadioSystems.BootstrapElements#1]
Great module.
Especially the tab module is real cool.

One thing is that when i try to add a panel-content item I get the following error:

![image](https://user-images.githubusercontent.com/1516981/27095688-3fe67c2a-5077-11e7-926c-aedf99ab379b.png)

**Comment by wharri220** [comment]
Thanks for pointing out this issue, I'll get to work on fixing it.

**Comment by wharri220** [comment]
This should be resolved! Let me know if you have further issues.

**Comment by giannik** [comment]
thank you. 
Works now.
